spring.application.name=fairshare

# Fast startup tweaks
spring.main.lazy-initialization=true
spring.jpa.open-in-view=false

# Dummy database config for compilation/startup (Render will override these via ENV vars)
spring.datasource.url=jdbc:mysql://localhost:3306/fairshare_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
